# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2024
customText = """
<a id="15" href="https://beian.miit.gov.cn/">è‹ICPå¤‡2023048510å·-2</a>&nbsp;
<a href="https://beian.mps.gov.cn/#/query/webSearch">
<img style="width:12px;height:14px" src="https://static.flowerinsnow.cn/ico/nismsp.png" alt="nismsp.png">
è‹å…¬ç½‘å®‰å¤‡32050502011681å·
</a>
"""
#customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
#emoji = "ğŸ¥"
subtitle = "æŠ½è±¡çš„ç²¾ç¥ä¸–ç•Œæœ€ç²¾å½©äº†"

[sidebar.avatar]
enabled = true
local = false
src = "/img/avatars/flowerinsnow.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "2024 å†¬èŠ±iceï¼Œä¿ç•™æ‰€æœ‰æƒåˆ©"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

# [opengraph.twitter]
# site = ""
# card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
# [comments]
# enabled = false
# provider = "disqus"

# [comments.disqusjs]
# shortname = ""
# apiUrl = ""
# apiKey = ""
# admin = ""
# adminLabel = ""

# [comments.utterances]
# repo = ""
# issueTerm = "pathname"
# label = ""

# [comments.remark42]
# host = ""
# site = ""
# locale = ""

# [comments.vssue]
# platform = ""
# owner = ""
# repo = ""
# clientId = ""
# clientSecret = ""
# autoCreateIssue = false

# [comments.waline]
# serverURL = ""
# lang = ""
# visitor = ""
# avatar = ""
# emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
# requiredMeta = ["name", "email", "url"]
# placeholder = ""

# [comments.waline.locale]
# admin = "Admin"

# [comments.twikoo]
# envId = ""
# region = ""
# path = ""
# lang = ""

# [comments.cactus]
# defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
# serverName = "cactus.chat"
# siteName = ""

# [comments.giscus]
# repo = ""
# repoID = ""
# category = ""
# categoryID = ""
# mapping = ""
# lightTheme = ""
# darkTheme = ""
# reactionsEnabled = 1
# emitMetadata = 0

# [comments.gitalk]
# owner = ""
# admin = ""
# repo = ""
# clientID = ""
# clientSecret = ""

# [comments.cusdis]
# host = ""
# id = ""
